from pathlib import Path

from src.config.settings import settings
from src.models.pull_request import PullRequestResult
from src.services.github_service import GitHubService


class PRAgent:

    def __init__(
        self,
        repository_path: str | Path | None = None,
        owner: str | None = None,
        repo_name: str | None = None,
        base_branch: str | None = None,
    ):
        self.repository_path = (
            Path(
                repository_path
                or settings.repository_path
            )
            .resolve()
        )

        self.base_branch = (
            base_branch
            or settings.github_base_branch
        )

        self.github_service = (
            GitHubService(
                owner=owner,
                repo_name=repo_name,
            )
        )

    def create_pull_request(
        self,
        ticket: dict,
        branch_name: str,
        changed_files: list[str],
        verification_result: dict,
        test_result: dict,
    ) -> PullRequestResult:

        ticket_id = str(
            ticket.get(
                "id",
                "ticket",
            )
        )

        ticket_title = ticket.get(
            "title",
            "AI Agent Changes",
        )

        title = (
            f"{ticket_id}: "
            f"{ticket_title}"
        )

        body = self._build_body(
            ticket=ticket,
            branch_name=branch_name,
            changed_files=changed_files,
            verification_result=verification_result,
            test_result=test_result,
        )

        return (
            self.github_service
            .create_pull_request(
                title=title,
                body=body,
                head_branch=branch_name,
                base_branch=self.base_branch,
            )
        )

    def _build_body(
        self,
        ticket: dict,
        branch_name: str,
        changed_files: list[str],
        verification_result: dict,
        test_result: dict,
    ) -> str:

        ticket_id = ticket.get(
            "id",
            "N/A",
        )

        ticket_title = ticket.get(
            "title",
            "N/A",
        )

        description = ticket.get(
            "description",
            "",
        )

        acceptance_criteria = ticket.get(
            "acceptance_criteria",
            [],
        )

        acceptance_text = "\n".join(
            f"- {criterion}"
            for criterion in acceptance_criteria
        )

        changed_files_text = "\n".join(
            f"- `{file}`"
            for file in changed_files
        )

        verification_status = (
            verification_result.get(
                "status",
                "UNKNOWN",
            )
        )

        verification_score = (
            verification_result.get(
                "score",
                "N/A",
            )
        )

        test_success = (
            test_result.get(
                "success",
                False,
            )
        )

        test_command = (
            test_result.get(
                "command",
                "",
            )
        )

        return f"""## AI Development Agent

### Ticket

**ID:** {ticket_id}

**Title:** {ticket_title}

### Description

{description}

### Acceptance Criteria

{acceptance_text or "- None provided"}

### Changed Files

{changed_files_text or "- None"}

### Verification

- Status: **{verification_status}**
- Score: **{verification_score}**

### Tests

- Status: **{"PASSED" if test_success else "FAILED"}**
- Command: `{test_command or "N/A"}`

### Branch

`{branch_name}`

---

This pull request was generated by the AI Development Agent.
"""


def create_pull_request(
    ticket: dict,
    branch_name: str,
    changed_files: list[str],
    verification_result: dict,
    test_result: dict,
    repository_path: str | Path | None = None,
    owner: str | None = None,
    repo_name: str | None = None,
    base_branch: str | None = None,
) -> dict:

    agent = PRAgent(
        repository_path=repository_path,
        owner=owner,
        repo_name=repo_name,
        base_branch=base_branch,
    )

    result = agent.create_pull_request(
        ticket=ticket,
        branch_name=branch_name,
        changed_files=changed_files,
        verification_result=verification_result,
        test_result=test_result,
    )

    return result.model_dump()